# This is a basic workflow to help you get started with Actions

name: Tracker 
on:
  # Triggers the workflow on push events
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called track
  track:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Clone-Repo
        run: sudo git clone https://geek0609:${{ secrets.GITHUB_TOKEN }}@github.com/geek0609/rom-tracker repo

      - name: Run main.py
        run: python3 repo/main.py
        env:
          BOT_API: ${{ secrets.BOT_API }}
          CHAT_ID: ${{ secrets.CHAT }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

