# This is a basic workflow to help you get started with Actions

name: Tracker0
on:
  # Triggers the workflow on push events
  push:
  # Should make sure it runs regularly
  schedule:
    - cron: '*/30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called track
  track:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/rom-tracker
          token: ${{ secrets.PAT }}
          ref: new-implementation

      - name: Run main.py
        run: ls && sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} roms.txt

      - name: Commit and Push
        run: sudo bash git_commit.sh

