# This is a basic workflow to help you get started with Actions

name: Update List
on:
  workflow_run:
    workflows: ["Tracker"]
    types:
      - completed

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called track
  track:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/rom-tracker
          token: ${{ secrets.PAT }}
          ref: new-implementation

      - name: Update List
        run: ls && sudo python3 update.py

      - name: Commit and Push Changes
        run: sudo bash git_update_list.sh
